-- !norm
-- Your files must start with the above line

-- !file store.go
-- Filename to write the generated output in

-- !package example
-- package name of the generated code

-- You can import packages by putting in a command like so !import "time"


-- Each block generates code depending on the "command". Supported commands are
-- "read", "read_one", "exec". The name following the command will be used in
-- the API names in autogenerated code. Having an intermediate `model` is optional.

-- !read GetUserListNoModel
-- !output ID int
-- !output Email string
-- !doc Retrieves all emails from the users table. Since there is no
-- !doc intermediate model, an output struct is autocreated which will contain only
-- !doc the fields specified in the output. Please make sure that the field names
-- !doc are capitalized.
SELECT id, email
FROM user
ORDER BY email ASC

-- !read GetUserEmailsNoModel
-- !output Email string
-- !doc Retrieves all emails from the users table. In this example, there is
-- !doc only one output field. Therefore an intermediate struct is also not needed,
-- !doc we just return a slice of the output type (string in this case)
SELECT email
FROM user
ORDER BY email ASC

-- !read GetUserListWithModel
-- !output ID int
-- !output Email string
-- !model User
-- !doc Retrieves all emails from the users table. In this example, an
-- !doc intermediate model is used. See `gen.go` for the model definition. This
-- !doc allows users to specify an arbitrary intermediate struct.
SELECT id, email
FROM user
ORDER BY email ASC

-- !exec AddUser
-- !input email string
-- !doc Add a user to the DB
INSERT into user(email)
VALUES ($1)

-- !exec DeleteAllUsers
-- !doc Deletes all users from the DB
DELETE FROM user

-- !read_one FindUser
-- !input email string
-- !output ID int
-- !output Email string
-- !doc Finds user by email
SELECT id, email
FROM USER
WHERE email = $1

-- !read_one FindUserEmail
-- !input email string
-- !output email string
-- !doc Finds user by email.
SELECT email
FROM USER
WHERE email = $1

-- !exec CreateUserTable
-- !doc Creates the user table
CREATE TABLE user (
	id integer primary key autoincrement,
	email text
)
